apiVersion: v1
kind: Service
metadata:
  name: api
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  type: NodePort
  selector:
    app: linkedin-wrapping-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000


